CREATE TABLE attendance_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enter_date TIMESTAMP,
    exit_date TIMESTAMP,
    stu_id NUMBER(5),
        CONSTRAINT stu_id_master_stu_id_fk FOREIGN KEY (stu_id)
        REFERENCES students(stu_id)
);
        
CREATE TABLE students (
    stu_id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stu_name varchar2(50) NOT NULL,
    stu_class varchar2(10),
    stu_group NUMBER(2),
    phone_number varchar2(13)
);


DESC students;
DESC attendance_log;

INSERT INTO students
VALUES (20241, '김주한', null, null, '010-7580-1210');
INSERT INTO students
VALUES (20242, '오한빛', null, null, '010-0000-0000');
INSERT INTO students
VALUES (20243, '고우석', null, null, '010-1111-1111');
INSERT INTO students
VALUES (20244, '백인권', null, null, '010-2222-2222');

SELECT * FROM students;
SELECT * FROM attendance_log;

desc students;

SELECT s.stu_id, s.stu_name, s.stu_class, l.enter_date, l.exit_date
FROM attendance_log l
JOIN students s
ON l.stu_id = s.stu_id
WHERE l.enter_date LIKE '%/%/&day %'
AND l.stu_id = 20241;

SELECT s.stu_id, s.stu_name, s.stu_class, l.enter_date, l.exit_date
FROM attendance_log l
JOIN students s
ON l.stu_id = s.stu_id
WHERE l.enter_date LIKE '%/&month/%'
AND l.stu_id = 20241;

COMMIT;